version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_KEY=base64:base64:A4PVuIFNxIqEg/u7jDpWWNO74pMwtKFURkghayqTMEQ=
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=cafe
            - DB_USERNAME=root
            - DB_PASSWORD=
            - COMPOSER_ALLOW_SUPERUSER=1
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=cafe
            - MYSQL_USER=root
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_PASSWORD=
        volumes:
            - ./mysql:/var/lib/mysql
